
name: myapp
description: "A modern weather application providing real-time weather updates, hourly and daily forecasts, and a user-friendly interface."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0-278.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  intl: ^0.20.2
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
